### ISSUE TITLE
db hint

### ISSUE THREAD

**Issue by vitaly-t** [kissmygritts/telemetr-api#1]
Great start! ;)

If you want to get the maximum value from `QueryFile`, make sure you are using its option `debug`, it is the most awesome part of the class, lets you auto-update queries during development without the necessity to restart your API service ;)

Once you start writing large queries, it becomes indispensible :wink:

Docs: https://github.com/vitaly-t/pg-promise#query-files

**Comment by kissmygritts** [comment]
Thanks for the input. I've been leaving out a lot of options for the sake of getting up and running, this is probably a poor practice.

**Comment by vitaly-t** [comment]
Some are more important than others :) like that `debug` option, which saves a lot of time debugging your SQL :wink:

**Comment by kissmygritts** [comment]
Just discovered how awesome and useful this is! If you hadn't given me the heads up, I may have waited. This is great.

**Comment by vitaly-t** [comment]
Just don't forget to switch `debug` off when the code goes to production, as it is IO-intensive ;)

**Comment by vitaly-t** [comment]
For this code:
```js
 if (q.species) {
    if (q.species.length > 1) {
      // QUESTION: this isn't working, how can i un-array an array
      where = pgp.as.format('WHERE captures.species IN ($(species))', q)
    } else {
      where = pgp.as.format('where captures.species = $(species)', q)
    }
  } else {
    where = ';'
  }
```
looks awkward...what you should do perhaps...

First, in your SQL use in the end:
```sql
WHERE ($1^)
```
And then your code would be:
```js
 if (q.species) {
      where = pgp.as.format('captures.species IN (${species:csv})', q);
  } else {
    where = 'true';
  }
```

**Comment by kissmygritts** [comment]
@vitaly-t, thanks for the help.  
What about this method? It has worked for all the cases I've tested.

``` javascript
if (Object.keys(q).length !== 0) {
    for (let x in q) {
      s.push(pgp.as.format(`${x} IN ($(${x}:csv))`, q))
    }
    where = s.reduce((prev, curr) => prev + ' AND ' + curr)
  } else {
    where = true
  }
```

**Comment by kissmygritts** [comment]
Change routes methods. I'm not using this query or method (for now).
